version: "3.6"

services:
  database:
    image: whek/sis_database
    environment:
      POSTGRES_USER: nodeserver
      POSTGRES_PASSWORD: nodeserverpassword
      POSTGRES_DB: datastorage
    ports:
      - 5432:5432
    deploy:
      placement:
        constraints: [node.hostname == pimanager1]

  api:
    image: whek/sis_node-server
    command: npm start
    restart: always
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
    depends_on:
      - database
    links:
      - database

# docker service create -e POSTGRES_PASSWORD=nodeserverpassword -e POSTGRES_USER=nodeserver -e POSTGRES_DB=datastorage  -p 5432:5432 --name data  whek/sis_database